# name: try/catch
# key: try
# --
try {
  $1
} catch (Exception $e) {
  $2
}